<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AiKiLocQR.Core\AiKiLocQR.Core.csproj" />
    <ProjectReference Include="..\AiKiLocQR.Crypto\AiKiLocQR.Crypto.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="assets\" />
  </ItemGroup>

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>

		<ApplicationIcon>assets\logo.ico</ApplicationIcon>

		<!-- Jeden plik EXE -->
		<PublishSingleFile>true</PublishSingleFile>
		<SelfContained>true</SelfContained>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
	</PropertyGroup>



</Project>
